name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/rangen .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/rangen

      - name: Deploy to GCP
        run: |
          gcloud run deploy rangen --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/rangen --platform managed --region us-central1
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
